spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?characterEncoding=utf8&useSSL=false&autoReconnect=true&&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8080

actable:
  table:
    auto: update
  model:
    pack: com.example.entity
  database:
    type: mysql
